src/titles/urls.py
from django.urls import path

from .views import IndexView, PickView, PickedView, AddView

app_name = 'titles'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('pick/', PickView.as_view(), name='pick'),
    path('picked/', PickedView.as_view(), name='picked'),
    path('add/', AddView.as_view(), name='add'),
]

src/users/urls.py
from django.urls import path

from users import views as v

app_name = 'users'
urlpatterns = [
    path('me/', v.MyProfileView.as_view(), name='my_profile'),
]

src/whichone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('titles.urls')),
    path('u/', include('allauth.urls')),
    path('u/', include('users.urls')),
    path('admin/', admin.site.urls),
]

src/titles/models.py
from django.db import models

from django_random_queryset import RandomManager

from users.models import User


class Title(models.Model):
    text = models.CharField(max_length=255, unique=True)
    picks = models.IntegerField(default=0)
    appearances = models.IntegerField(default=0)
    users = models.ManyToManyField(User, 'picks')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='titles',
    )

    objects = RandomManager()

    @property
    def winrate(self):
        return round(self.picks / self.appearances * 100, 1)

    def __str__(self):
        return self.text

src/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(unique=True)

src/titles/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from titles.models import Title
from titles.services import (
    IndexServiceMixin,
    PickServiceMixin,
    PickedServiceMixin,
)


class IndexView(IndexServiceMixin, ListView):
    model = Title
    template_name = 'titles/index.html'
    context_object_name = 'titles'


class PickView(LoginRequiredMixin, PickServiceMixin, ListView):
    model = Title
    template_name = 'titles/pick.html'
    context_object_name = 'titles'


class PickedView(LoginRequiredMixin, PickedServiceMixin, DetailView):
    model = Title


class AddView(LoginRequiredMixin, CreateView):
    model = Title
    template_name = 'titles/add.html'
    fields = ('text', )
    success_url = reverse_lazy('titles:add')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

src/users/views.py
from django.views.generic import View

from users.models import User
from users.services import MyProfileServiceMixin


class MyProfileView(MyProfileServiceMixin, View):
    model = User
    template_name = 'users/my_profile.html'

src/templates/wrapper.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
  rel="stylesheet">
  <link type="text/css" rel="stylesheet" 
  href="{% static 'css/materialize.css' %}"  media="screen,projection">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="stylesheet" href="{% static 'css/titles.css' %}">

  <title>{% block title %}
    `title` not overriden
  {% endblock %} - Which One?</title>

  <script type="text/javascript"
  src="{% static 'js/materialize.js' %}"></script>
</head>
<body>

  <nav class="teal accent-4">
    <div class="nav-wrapper container">
      <a href="{% url 'titles:index' %}" class="brand-logo">
        <img src="{% static 'imgs/logo.png' %}" alt="Which One?">
      </a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        {% if user.is_authenticated %}
          <li><a href="{% url 'titles:add' %}">Add Title</a></li>
          <li><a href="{% url 'users:my_profile' %}">
            {{ user.username }}
          </a></li>
          <li><a href="{% url 'account_logout' %}">Log Out</a></li>
        {% else %}
          <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
          <li><a href="{% url 'account_login' %}">Log In</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <div class="container">
    <div class="row">
      <div class="col s12 m9 l8">
        <div class="row" style="margin-bottom: 0;">
          <header class="not-for-small">
            {% block header %}`header` not overriden{% endblock %}
          </header>
        </div>

        <div class="row">
          <section class="content">
            {% block content %}
              `content` not overriden
            {% endblock %}
          </section>
        </div>
      </div>

      <div class="col s0 m3 l4">
        <div class="sidebar not-for-small">
          The sidebar
        </div>
      </div>
    </div>
  </div>

  <!-- Flash messages -->
  {% for message in messages %}
    <div class="flash-message-hidden" id="flash{{ forloop.counter }}">
      {{ message }}
    </div>
  {% endfor %}
  <script>
    for (i = 1; i <= {{ messages|length }}; i++) {
      var message = document.getElementById(
        `flash${i}`
      ).textContent;
      M.toast({html: message});
    }
  </script>

</body>
</html>

src/titles/templates/titles/add.html
{% extends 'wrapper.html' %}


{% block title %}Add Title{% endblock %}

{% block header %}
  <p class="flow-text"><strong>Add Title</strong></p>
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"
    class="btn btn-large waves-effect waves-light">
      Add <i class="material-icons right">add</i>
    </button>
  </form>
{% endblock %}

src/titles/templates/titles/index.html
{% extends 'wrapper.html' %}


{% block title %}Titles{% endblock %}

{% block header %}
  <p class="flow-text"><strong>Start right now!</strong></p>
{% endblock %}

{% block content %}
  <a href="{% url 'titles:pick' %}"
  class="btn btn-large teal accent-4">
    Start Picking from <b>{{ titles.count }}</b> titles
    <i class="material-icons right">chevron_right</i>
  </a>
{% endblock %}

src/titles/templates/titles/pick.html
{% extends 'wrapper.html' %}


{% block title %}Pick{% endblock %}

{% block header %}
  <p class="flow-text"><strong>Which title sounds better?</strong></p>
{% endblock %}

{% block content %}
  <div class="row">
    {% for title in titles %}
      <div class="col s12 m6">
        <form action="{% url 'titles:picked' %}" method="post"
        class="inline-block pick">
          {% csrf_token %}

          <input type="hidden" name="picked" value="{{ title.id }}">

          <input type="submit" value="{{ title.text }}"
          class="black-text card-panel white pick">
        </form>
      </div>
    {% endfor %}
  </div>
{% endblock %}

src/users/templates/users/my_profile.html
{% extends 'wrapper.html' %}


{% block title %}{{ user.username }}{% endblock %}


{% block header %}
  <p class="flow-text"><strong>{{ user.username }} - Profile</strong></p>
{% endblock %}

{% block content %}
  <div class="my-titles">
    <div class="row">
      <ul class="collection with-header">
        <li class="collection-header"><h4>My Titles</h4></li>
        <li class="collection-item">
          <div>
            placeholder
            <div class="secondary-content">
              101
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
  <div class="my-picks">
    <div class="row">
      <ul class="collection with-header">
        <li class="collection-header"><h4>My Picks</h4></li>
        {% for pick in user.picks.all %}
          <li class="collection-item">
            <div>
              {{ pick.text }}
              <div class="secondary-content">
                {{ pick.winrate }}%
              </div>
            </div>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}